### ISSUE TITLE
Clicking on Flickr thumbnails, opens 404 page

### ISSUE THREAD

**Issue by goldenratio** [maban/console-browsers#19]
Clicking on Flickr thumbnails, opens 404 page

```
<script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?show_name=1&count=3&display=latest&size=m&layout=h&context=in%2Fpool-2101283%40N20%2F&source=group_tag&group=2101283%40N20&tag=xbox+one">
</script>
```

after investigation, the culprit is `context`, flickr doesn't decode it.

**Comment by maban** [comment]
@goldenratio Thanks for flagging this up, and telling me what exactly was broken! I've removed that string from all the files and the links work again. :smile:
